# Generated by Django 4.1 on 2024-09-24 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cat_name", models.CharField(max_length=200)),
                ("cat_parent", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lecturers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lecturer_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Sites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(max_length=50)),
                ("site_url", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Lectures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lec_title", models.CharField(max_length=200)),
                ("lec_img_link", models.CharField(max_length=500)),
                ("lec_link", models.CharField(max_length=500)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=2)),
                ("review_count", models.IntegerField(max_length=10)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lecture.categories",
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lecture.lecturers",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lecture.sites",
                    ),
                ),
            ],
        ),
    ]
