# Generated by Django 4.1 on 2024-09-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lectures",
            name="review_count",
            field=models.IntegerField(),
        ),
    ]
